version: '3.5'

services:
  app:
    build: ./
    ports:
      - '8080:8080'
    container_name: 'test'
    restart: unless-stopped
    depends_on:
      - posti
    environment:
      - DB_HOST=posti
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_PORT=5432
      - DB_NAME=postgres
      - SSL_MODE=disable
      - API_PORT=8080
      - ANOTHER_API=8082
  posti:
    restart: unless-stopped
    image: postgres
    ports:
      - '5432:5432'
    environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=postgres